app/__init__.py
from flask import Flask

def create_app(config_name):
    app = Flask(__name__)

    from .orgs import orgs as orgs_blueprint
    app.register_blueprint(orgs_blueprint)
    
    from .indv import indv as indv_blueprint
    app.register_blueprint(indv_blueprint,url_prefix='/indv')

    return app

app/indv/__init__.py
from flask import Blueprint

indv = Blueprint('indv', __name__)

from . import routes

app/indv/routes.py
from flask import render_template, request, g, session, redirect, url_for
from . import indv
import requests
from ..apicode import apiresult, userapiresult

@indv.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        user_name = request.form['indvsearch'].strip()
        print user_name
        if not user_name:
            error = "What do you want to search?"
            return render_template('indv/index.html', error=error)
        return redirect(url_for('indv.sort_by_name',user_name=user_name))
    return render_template('indv/index.html')

@indv.route('/SortByName/<user_name>')
def sort_by_name(user_name):
    json_obj = userapiresult(user_name)
    if len(json_obj) !=0:
        try:
            json_obj['message']
            context_dict = {"message":"No such user exists!"}
            return render_template('indv/results.html',context_dict=context_dict)
        except:
            sorted_list = sorted(json_obj, key=lambda k: k['name'].title(), reverse = False)
            return render_template('indv/sortbyname.html',user_name=user_name,sorted_list=sorted_list)
    else:
        context_dict = {"message":"No such user exists!"}
        return render_template('indv/results.html',context_dict=context_dict)


@indv.route('/SortByDate/<user_name>')
def sort_by_date(user_name):
    json_obj = userapiresult(user_name)
    sorted_list = sorted(json_obj, key=lambda k: k['created_at'], reverse = True)
    return render_template('indv/sortbydate.html',user_name=user_name,sorted_list=sorted_list)

@indv.route('/SortByIssues/<user_name>')
def sort_by_issues(user_name):
    json_obj = userapiresult(user_name)
    sorted_list = sorted(json_obj, key=lambda k: k['open_issues_count'], reverse = True)
    return render_template('indv/sortbyissues.html',user_name=user_name,sorted_list=sorted_list)

@indv.route('/SortByStars/<user_name>')
def sort_by_stars(user_name):
    json_obj = userapiresult(user_name)
    sorted_list = sorted(json_obj, key=lambda k: k['stargazers_count'], reverse = True)
    return render_template('indv/sortbystars.html',user_name=user_name,sorted_list=sorted_list)

app/orgs/__init__.py
from flask import Blueprint

orgs = Blueprint('orgs', __name__)

from . import routes

app/orgs/routes.py
from flask import render_template, request, g, session, redirect, url_for
from . import orgs
from ..apicode import apiresult
from app import redis_store
import json, pickle


@orgs.route('/', methods=['GET', 'POST'])
def index():
    redis_store.set('json_data', None)
    redis_store.set('newsortedlist',None)
    if request.method == 'POST':
        org_name = request.form['orgsearch'].strip().title()
        if not org_name:
            error = "What do you want to search?"
            return render_template('orgs/index.html', error=error)
        return redirect(url_for('orgs.sort_by_name',org_name=org_name))
    return render_template('orgs/index.html')


@orgs.route('/SortByName/<org_name>')
def sort_by_name(org_name):
    json_obj = apiresult(org_name)
    if len(json_obj) !=0:
        try:
            json_obj['message']
            context_dict = {"message":"No such organisation exists!"}
            return render_template('orgs/results.html',context_dict=context_dict)
        except:
            l = []
            sorted_list = sorted(json_obj, key=lambda k: k['name'].title(), reverse = False)
            for row in sorted_list:
                l.append(str(row['language']))
            newlist = list(set(l))
            if 'None' in newlist:
                newlist = ['Not Assigned' if x=='None' else x for x in newlist]
            newsortedlist = sorted(newlist)
            return render_template('orgs/sortbyname.html',org_name=org_name,sorted_list=sorted_list,newsortedlist=newsortedlist)
    else:
        context_dict = {"message":"No such organisation exists!"}
        return render_template('orgs/results.html',context_dict=context_dict)



@orgs.route('/SortByDate/<org_name>')
def sort_by_date(org_name):
    json_obj = json.loads(redis_store.get('json_data'))
    sorted_list = sorted(json_obj, key=lambda k: k['created_at'], reverse = True)
    for row in sorted_list:
        l.append(str(row['language']))
    newlist = list(set(l))
    if 'None' in newlist:
        newlist = ['Not Assigned' if x=='None' else x for x in newlist]
    newsortedlist = sorted(newlist)
    return render_template('orgs/sortbydate.html',org_name=org_name,sorted_list=sorted_list,newsortedlist=newsortedlist)

@orgs.route('/SortByIssues/<org_name>')
def sort_by_issues(org_name):
    json_obj = json.loads(redis_store.get('json_data'))
    sorted_list = sorted(json_obj, key=lambda k: k['open_issues'], reverse = True)
    for row in sorted_list:
        l.append(str(row['language']))
    newlist = list(set(l))
    if 'None' in newlist:
        newlist = ['Not Assigned' if x=='None' else x for x in newlist]
    newsortedlist = sorted(newlist)
    return render_template('orgs/sortbyissues.html',org_name=org_name,sorted_list=sorted_list,newsortedlist=newsortedlist)

@orgs.route('/SortByLanguage/<org_name>/<item>')
def sort_by_language(org_name,item):
    json_obj = json.loads(redis_store.get('json_data'))
    sorted_list = sorted(json_obj, key=lambda k: k['name'].title(), reverse = False)
    for row in sorted_list:
        l.append(str(row['language']))
    newlist = list(set(l))
    if 'None' in newlist:
        newlist = ['Not Assigned' if x=='None' else x for x in newlist]
    newsortedlist = sorted(newlist)
    return render_template('orgs/sortbylanguage.html',org_name=org_name,sorted_list=sorted_list,item=item,newsortedlist=newsortedlist)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!--
    <link rel="shortcut icon" type="image/png" href=""/>
    -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    {% block cssfile %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% block jsfile %}{% endblock %}

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('orgs.index') }}">GitSearch, Making Github Search easier!!!</a>
            </div>
        </div>
        {% block navbar %}{% endblock %}
    </nav>

    {% block body %}
{% endblock %}
<footer class="footer">
      <div class="container">
        <p class="text-muted">Developed by <a href="http://sagaragarwal94.me">Sagar Chand Agarwal</a> and <a href="https://github.com/hiteshgarg14">Hitesh Garg</a>. Copyright @ 2016. Licensed under MIT.</p>
      </div>
    </footer>

</body>
</html>

app/templates/home/results.html
{% extends 'base.html' %}

{% block title %}GitSearch{% endblock %}

{% block cssfile %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/results.css') }}"/>
{% endblock %}


{% block body %}
<div class="container">
       <div class="row">
          <div class="col-md-9">
                <!-- Page Content -->
                         <div class="col-md-3" >
                            <div class="container">
                                <hgroup class="mb20">
                                    {% if context_dict %}
                                        <h3>{{ context_dict['message'] }}</h3>
                                    {% else %}
                                        <h1>Search Results</h1>
                                        <h2 class="lead">results were found for the search for <strong class="text-danger">{{org_name}}</strong></h2>
                                </hgroup>
                                        {% for row in sorted_list %}
                                            <section class="col-md-9">
                                            <article class="search-result row">
                                            <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
                                                  <h3><a href="https://github.com/{{org_name}}/{{row['name']}}" title="">{{row['name']}}</a></h3>
                                                  <p>Created Date:- {{row['created_at']}} </p>
                                                  <p>Issues:- {{row['open_issues']}} </p>
                                                  <br />
                                                  <br />
                                            </div>
                                            <span class="clearfix borda"></span>
                                            </article>
                                            </section>
                                        {% endfor %}
                            </div>
                        </div>
            </div>
            <div class="col-md-3" id="sortbar">
                <div class="btn-group">
                    <button type="button" class="btn btn-default">Sort By</button>
                    <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle"><span class="caret"></span></button>

                     <ul class="dropdown-menu">
                        <li><a href="{{ url_for('home.sort_by_name',org_name=org_name) }}" ><span class="{% block dropdownok1 %}{% endblock %}"></span> Name</a></li>
                        <li><a href="{{ url_for('home.sort_by_date',org_name=org_name) }}" ><span class="{% block dropdownok2 %}{% endblock %}"></span> Created Date</a></li>
                        <li><a href="{{ url_for('home.sort_by_issues',org_name=org_name) }}" ><span class="{% block dropdownok3 %}{% endblock %}"></span> Issues</a></li>
                     </ul>
                </div>
            </div>
    {% endif %}
  </div>
</div>

{% endblock %}

app/templates/home/sortbydate.html
{% extends 'home/results.html' %}

{% block dropdownok2 %}glyphicon glyphicon-ok pull-right{% endblock %}

app/templates/home/sortbyissues.html
{% extends 'home/results.html' %}

{% block dropdownok3 %}glyphicon glyphicon-ok pull-right{% endblock %}

app/templates/home/sortbyname.html
{% extends 'home/results.html' %}

{% block dropdownok1 %}glyphicon glyphicon-ok pull-right{% endblock %}

app/templates/indv/index.html
{% extends 'base.html' %}

{% block title %}Github Individual Search{% endblock %}

{% block cssfile %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css') }}"/>
{% endblock %}

{% block jsfile %}
<script src="{{ url_for('static',filename='js/main.js') }}"></script>
{% endblock %}

{% block body %}
<div class="container" id="footer">
    <div class="row" id='eg2'>
        <div class="col-md-6 col-md-offset-3" id="eg1">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="{{ url_for('orgs.index') }}"  id="login-form-link">Organisation</a>
                        </div>
                        <div class="col-xs-6">
                            <a href="{{ url_for('indv.index') }}" class="active" id="register-form-link">Individual</a>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {% if error %}
                                {{ error }}
                            {% endif %}
                            <form id="login-form" action="{{url_for('indv.index')}}" method="post" role="form" style="display: block;">
                                <div class="form-group">
                                    <input type="text" name="indvsearch" id="username" tabindex="1" class="form-control" placeholder="Search" >

                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Search" >
                                        </div>
                                    </div>
                                </div>

                            </form>
                            <form id="register-form" action="{{url_for('indv.index')}}" method="post" role="form" style="display: none;">
                                <div class="form-group">
                                    <input type="text" name="indvsearch" id="username" tabindex="1" class="form-control" placeholder="Search" >
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Search" >
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/indv/results.html
{% extends 'base.html' %}

{% block title %}GitSearch{% endblock %}

{% block cssfile %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/results.css') }}"/>
{% endblock %}


{% block body %}
<div class="container">
       <div class="row">
          <div class="col-md-9">
                <!-- Page Content -->
                         <div class="col-md-3" >
                            <div class="container">
                                <hgroup class="mb20">
                                    {% if context_dict %}
                                        <h3>{{ context_dict['message'] }}</h3>
                                    {% else %}
                                        <h1>Search Results</h1>
                                        <h2 class="lead">results were found for the search for <strong class="text-danger">{{user_name}}</strong></h2>
                                </hgroup>
                                {% block language %}{% endblock %}
                                {% block basic %}{% endblock %}

                            </div>
                        </div>
            </div>
                                <div class="col-md-3" id="sortbar">
                                <div class="btn-group">
                                <button type="button" class="btn btn-default">Sort By</button>
                                <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle"><span class="caret"></span></button>

                                <ul class="dropdown-menu">
                                <li><a href="{{ url_for('indv.sort_by_name',user_name=user_name) }}" ><span class="{% block dropdownok1 %}{% endblock %}"></span> Name</a></li>
                                <li><a href="{{ url_for('indv.sort_by_date',user_name=user_name) }}" ><span class="{% block dropdownok2 %}{% endblock %}"></span> Created Date</a></li>
                                <li><a href="{{ url_for('indv.sort_by_issues',user_name=user_name) }}" ><span class="{% block dropdownok3 %}{% endblock %}"></span> Issues</a></li>
                                <li><a href="{{ url_for('indv.sort_by_stars',user_name=user_name) }}" ><span class="{% block dropdownok4 %}{% endblock %}"></span> Stars</a></li>
                                </ul>
                                </div>
                                </div>



                                {% endif %}
                            </div>
                        </div>

{% endblock %}

app/templates/indv/sortbydate.html
{% extends 'indv/results.html' %}

{% block basic %}
{% for row in sorted_list %}
    <section class="col-md-9">
    <article class="search-result row">
    <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
          <h3><a href="https://github.com/{{user_name}}/{{row['name']}}" title="">{{row['name']}}</a></h3>
          <p>Created Date:- {{row['created_at']}} </p>
          <p>Issues:- {{row['open_issues_count']}} </p>
          <p>Stars:- {{row['stargazers_count']}} </p>
          <br />
          <br />
    </div>
    <span class="clearfix borda"></span>
    </article>
    </section>
{% endfor %}
{% endblock %}

{% block dropdownok2 %}glyphicon glyphicon-ok pull-right{% endblock %}

app/templates/indv/sortbyissues.html
{% extends 'indv/results.html' %}

{% block basic %}
{% for row in sorted_list %}
    <section class="col-md-9">
    <article class="search-result row">
    <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
          <h3><a href="https://github.com/{{user_name}}/{{row['name']}}" title="">{{row['name']}}</a></h3>
          <p>Created Date:- {{row['created_at']}} </p>
          <p>Issues:- {{row['open_issues_count']}} </p>
          <p>Stars:- {{row['stargazers_count']}} </p>
          <br />
          <br />
    </div>
    <span class="clearfix borda"></span>
    </article>
    </section>
{% endfor %}
{% endblock %}

{% block dropdownok3 %}glyphicon glyphicon-ok pull-right{% endblock %}

app/templates/indv/sortbyname.html
{% extends 'indv/results.html' %}

{% block basic %}
{% for row in sorted_list %}
    <section class="col-md-9">
    <article class="search-result row">
    <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
          <h3><a href="https://github.com/{{user_name}}/{{row['name']}}" title="">{{row['name']}}</a></h3>
          <p>Created Date:- {{row['created_at']}} </p>
          <p>Issues:- {{row['open_issues_count']}} </p>
          <p>Stars:- {{row['stargazers_count']}} </p>
          <br />
          <br />
    </div>
    <span class="clearfix borda"></span>
    </article>
    </section>
{% endfor %}
{% endblock %}

{% block dropdownok1 %}glyphicon glyphicon-ok pull-right{% endblock %}

app/templates/indv/sortbystars.html
{% extends 'indv/results.html' %}

{% block basic %}
{% for row in sorted_list %}
    <section class="col-md-9">
    <article class="search-result row">
    <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
          <h3><a href="https://github.com/{{user_name}}/{{row['name']}}" title="">{{row['name']}}</a></h3>
          <p>Created Date:- {{row['created_at']}} </p>
          <p>Issues:- {{row['open_issues_count']}} </p>
          <p>Stars:- {{row['stargazers_count']}} </p>
          <br />
          <br />
    </div>
    <span class="clearfix borda"></span>
    </article>
    </section>
{% endfor %}
{% endblock %}

{% block dropdownok4 %}glyphicon glyphicon-ok pull-right{% endblock %}

app/templates/orgs/index.html
{% extends 'base.html' %}

{% block title %}Github Organisation Search{% endblock %}

{% block cssfile %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css') }}"/>
{% endblock %}

{% block jsfile %}
<script src="{{ url_for('static',filename='js/main.js') }}"></script>
{% endblock %}

{% block body %}
<div class="container" id="footer">
    <div class="row" id='eg2'>
        <div class="col-md-6 col-md-offset-3" id="eg1">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="{{ url_for('orgs.index') }}" class="active" id="login-form-link">Organisation</a>
                        </div>
                        <div class="col-xs-6">
                            <a href="{{ url_for('indv.index') }}" id="register-form-link">Individual</a>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {% if error %}
                                {{ error }}
                            {% endif %}
                            <form id="login-form" action="{{url_for('orgs.index')}}" method="post" role="form" style="display: block;">
                                <div class="form-group">
                                    <input type="text" name="orgsearch" id="username" tabindex="1" class="form-control" placeholder="Search" >

                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Search" >
                                        </div>
                                    </div>
                                </div>

                            </form>
                            <form id="register-form" action="{{url_for('indv.index')}}" method="post" role="form" style="display: none;">
                                <div class="form-group">
                                    <input type="text" name="indvsearch" id="username" tabindex="1" class="form-control" placeholder="Search" >
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Search" >
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/orgs/results.html
{% extends 'base.html' %}

{% block title %}GitSearch{% endblock %}

{% block cssfile %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/results.css') }}"/>
{% endblock %}


{% block body %}
<div class="container">
       <div class="row">
          <div class="col-md-9">
                <!-- Page Content -->
                         <div class="col-md-3" >
                            <div class="container">
                                <hgroup class="mb20">
                                    {% if context_dict %}
                                        <h3>{{ context_dict['message'] }}</h3>
                                    {% else %}
                                        <h1>Search Results</h1>
                                        <h2 class="lead">results were found for the search for <strong class="text-danger">{{org_name}}</strong></h2>
                                </hgroup>
                                {% block language %}{% endblock %}
                                {% block basic %}{% endblock %}

                            </div>
                        </div>
            </div>
                                <div class="col-md-3" id="sortbar">
                                <div class="btn-group">
                                <button type="button" class="btn btn-default">Sort By</button>
                                <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle"><span class="caret"></span></button>

                                <ul class="dropdown-menu">
                                <li><a href="{{ url_for('orgs.sort_by_name',org_name=org_name) }}" ><span class="{% block dropdownok1 %}{% endblock %}"></span> Name</a></li>
                                <li><a href="{{ url_for('orgs.sort_by_date',org_name=org_name) }}" ><span class="{% block dropdownok2 %}{% endblock %}"></span> Created Date</a></li>
                                <li><a href="{{ url_for('orgs.sort_by_issues',org_name=org_name) }}" ><span class="{% block dropdownok3 %}{% endblock %}"></span> Issues</a></li>
                                </ul>
                                </div>
                                </div>

                                <div class="col-md-3" id="sortbar" style="margin-top: 10px;">
                                <div class="btn-group">
                                <button type="button" class="btn btn-default">Language</button>
                                <button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle"><span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    {% block exp %}
                                {% for item in newsortedlist %}
                                <li><a href="{{ url_for('orgs.sort_by_language',org_name=org_name,item=item) }}" ><span ></span>{{ item }}</a></li>
                                {% endfor %}
                                {% endblock %}
                                </ul>
                                </div>
                                </div>

                                {% endif %}
                            </div>
                        </div>

{% endblock %}

app/templates/orgs/sortbydate.html
{% extends 'orgs/results.html' %}

{% block basic %}
{% for row in sorted_list %}
    <section class="col-md-9">
    <article class="search-result row">
    <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
          <h3><a href="https://github.com/{{org_name}}/{{row['name']}}" title="">{{row['name']}}</a></h3>
          <p>Created Date:- {{row['created_at']}} </p>
          <p>Issues:- {{row['open_issues']}} </p>
          <br />
          <br />
    </div>
    <span class="clearfix borda"></span>
    </article>
    </section>
{% endfor %}
{% endblock %}

{% block dropdownok2 %}glyphicon glyphicon-ok pull-right{% endblock %}

app/templates/orgs/sortbyissues.html
{% extends 'orgs/results.html' %}

{% block basic %}
{% for row in sorted_list %}
    <section class="col-md-9">
    <article class="search-result row">
    <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
          <h3><a href="https://github.com/{{org_name}}/{{row['name']}}" title="">{{row['name']}}</a></h3>
          <p>Created Date:- {{row['created_at']}} </p>
          <p>Issues:- {{row['open_issues']}} </p>
          <br />
          <br />
    </div>
    <span class="clearfix borda"></span>
    </article>
    </section>
{% endfor %}
{% endblock %}

{% block dropdownok3 %}glyphicon glyphicon-ok pull-right{% endblock %}

app/templates/orgs/sortbylanguage.html
{% extends 'orgs/results.html' %}

{% block language %}
    {% for row in sorted_list %}
        {% if row['language'] == item %}
                <section class="col-md-9">
                <article class="search-result row" >
                <div class="col-xs-12 col-sm-12 col-md-7 excerpet" >
                      <h3><a href="https://github.com/{{org_name}}/{{row['name']}}" title="">{{row['name']}}</a></h3>
                      <p>Created Date:- {{row['created_at']}} </p>
                      <p>Issues:- {{row['open_issues']}} </p>
                      <br />

                      <br />
                </div>
                <span class="clearfix borda"></span>
                </article>
                </section>
        {% endif %}
        {% if row['language'] not in newsortedlist and item=='Not Assigned'%}
        <section class="col-md-9">
        <article class="search-result row">
        <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
              <h3><a href="https://github.com/{{org_name}}/{{row['name']}}" title="">{{row['name']}}</a></h3>
              <p>Created Date:- {{row['created_at']}} </p>
              <p>Issues:- {{row['open_issues']}} </p>
              <br />

              <br />
        </div>
        <span class="clearfix borda"></span>
        </article>
        </section>
        {% endif %}

    {% endfor %}


{% endblock %}
{% block exp %}
{% for value in newsortedlist %}
{% if value == item %}
<li><a href="{{ url_for('orgs.sort_by_language',org_name=org_name,item=value) }}" ><span class="glyphicon glyphicon-ok pull-right"></span>{{ value }}</a></li>
{%else%}
<li><a href="{{ url_for('orgs.sort_by_language',org_name=org_name,item=value) }}" ><span ></span>{{ value }}</a></li>
{% endif %}
{% endfor %}
{% endblock %}

app/templates/orgs/sortbyname.html
{% extends 'orgs/results.html' %}

{% block basic %}
{% for row in sorted_list %}
    <section class="col-md-9">
    <article class="search-result row">
    <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
          <h3><a href="https://github.com/{{org_name}}/{{row['name']}}" title="">{{row['name']}}</a></h3>
          <p>Created Date:- {{row['created_at']}} </p>
          <p>Issues:- {{row['open_issues']}} </p>
          <br />
          <br />
    </div>
    <span class="clearfix borda"></span>
    </article>
    </section>
{% endfor %}
{% endblock %}

{% block dropdownok1 %}glyphicon glyphicon-ok pull-right{% endblock %}